register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::getTokenUser

test:
  path: /api/test
  controller: App\Controller\ApiController::test



advertisement_create_controller:
  path: /api/advertisement
  controller: App\Controller\AdvertisementCreateController
  methods: POST

advertisement_get_controller:
  path: /api/advertisement/{id}
  controller: App\Controller\AdvertisementGetController
  methods: GET
