register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::getTokenUser

  
  
  # API
health-check_get:
  path: /health-check
  controller: App\Controller\ApiController::healthCheck
  methods: GET

advertisement_create_controller:
  path: /api/advertisement
  controller: App\Controller\AdvertisementCreateController
  methods: POST

advertisement_update_controller:
  path: /api/advertisement/{id}
  controller: App\Controller\AdvertisementUpdateController
  methods: PUT

advertisement_update_partial_controller:
  path: /api/advertisement/{id}
  controller: App\Controller\AdvertisementUpdatePartialController
  methods: PATCH

advertisement_get_controller:
  path: /api/advertisement/{id}
  controller: App\Controller\AdvertisementGetController
  methods: GET

advertisement_search_by_criteria_controller:
  path: /api/advertisements
  controller: App\Controller\AdvertisementSearchByCriteriaController
  methods: GET

advertisement_delete_controller:
  path: /api/advertisement/{id}
  controller: App\Controller\AdvertisementDeleteController
  methods: DELETE
